version: '3'

services:
  unused-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/unused-pypy:0.0.0
    volumes:
      - ./pyproject.toml:/opt/unused/pyproject.toml
      - ./README.md:/opt/unused/README.md
      - ./setup.py:/opt/unused/setup.py
      - ./tests:/opt/unused/tests
      - ./unused:/opt/unused/unused
    entrypoint: pytest
